from collections.abc import Mapping, Sequence
from typing import TypeAlias

from PySide6.QtCore import QObject, QSize, Qt
from PySide6.QtGui import QColor, QIcon, QPixmap
from PySide6.QtWidgets import QWidget

from pyside_iconify._config import DefaultConfig
from pyside_iconify.core.types import IconData, RGBA

ColorScalar: TypeAlias = str | Sequence[int | float] | RGBA | QColor | Qt.GlobalColor
ColorMapping: TypeAlias = Mapping[ColorScalar, ColorScalar]
ColorValue: TypeAlias = ColorScalar | ColorMapping

class IconifyError(Exception): ...
class InvalidIconNameError(IconifyError): ...
class InvalidIconDataError(IconifyError): ...
class IconNotFoundError(IconifyError): ...
class InvalidColorError(IconifyError): ...
class InvalidSizeError(IconifyError): ...
class InvalidRotationError(IconifyError): ...
class InvalidOpacityError(IconifyError): ...
class DuplicateIconError(IconifyError): ...
class UnsupportedSvgError(IconifyError): ...
class UnsafeIconDataError(IconifyError): ...
class WrongThreadError(IconifyError): ...
class NoApplicationError(IconifyError): ...
class IconNotLoadedError(IconifyError): ...
class UnsupportedTargetError(IconifyError): ...
class NetworkError(IconifyError): ...
class OfflineError(IconifyError): ...
class RateLimitError(IconifyError): ...
class ServerError(IconifyError): ...
class InvalidResponseError(IconifyError): ...
class ResponseTooLargeError(IconifyError): ...
class RequestCancelledError(IconifyError): ...
class ClientClosedError(IconifyError): ...

class IconWidget(QWidget):
    def __init__(
        self,
        icon: str | IconData,
        *,
        size: int | float | str | tuple[int | float, int | float] | QSize | None = None,
        color: ColorValue | None = None,
        light_color: ColorValue | None = None,
        dark_color: ColorValue | None = None,
        opacity: float | None = None,
        width: int | float | str | None = None,
        height: int | float | str | None = None,
        rotate: float = 0,
        spin: bool = False,
        spin_period: float | None = None,
        h_flip: bool = False,
        v_flip: bool = False,
        qss: str | None = None,
        fallback: str | None = ...,
        parent: QWidget | None = None,
    ) -> None: ...
    def iconName(self) -> str: ...
    def setIcon(self, icon: str) -> None: ...
    def setSize(
        self, value: int | float | str | tuple[int | float, int | float] | QSize
    ) -> None: ...
    def setColor(self, value: ColorValue | None) -> None: ...
    def setLightColor(self, value: ColorValue | None) -> None: ...
    def setDarkColor(self, value: ColorValue | None) -> None: ...
    def setOpacity(self, value: float) -> None: ...
    def setRotation(self, value: float) -> None: ...
    def setSpin(self, enabled: bool) -> None: ...
    def setFlips(self, horizontal: bool, vertical: bool) -> None: ...

def add_icon(name: str, data: IconData | str, *, replace: bool = False) -> None: ...
def add_collection(
    collection: Mapping[str, object], *, replace: bool = False
) -> None: ...
def get_icon(
    icon: str | IconData,
    *,
    size: int | float | str | tuple[int | float, int | float] | QSize | None = None,
    color: ColorValue | None = None,
    light_color: ColorValue | None = None,
    dark_color: ColorValue | None = None,
    opacity: float | None = None,
    width: int | float | str | None = None,
    height: int | float | str | None = None,
    rotate: float = 0,
    spin: bool = False,
    h_flip: bool = False,
    v_flip: bool = False,
) -> QIcon: ...
def get_pixmap(
    icon: str | IconData, *, size: object | None = None, **options: object
) -> QPixmap: ...
def get_icon_data(icon: str) -> IconData: ...
def mark_pending(icon: str) -> None: ...
def get_icon_colors(icon: str) -> tuple[str, ...]: ...
def is_monotone(icon: str) -> bool: ...
def hex_argb(value: str) -> RGBA: ...
def hex_rgba(value: str) -> RGBA: ...
def get_default_config() -> DefaultConfig: ...
def set_default_config(
    *,
    size: int | float | str | tuple[int | float, int | float] | QSize | None = ...,
    color: ColorValue | None = ...,
    light_color: ColorValue | None = ...,
    dark_color: ColorValue | None = ...,
    opacity: float | None = ...,
    fallback: str | None = ...,
    disabled_opacity: float | None = ...,
    spin_period: float | None = ...,
) -> DefaultConfig: ...
def set_disabled_opacity(value: float) -> None: ...
def set_cache_limits(
    *, pixmap_mib: int | None = None, data_entries: int | None = None
) -> None: ...
def set_offline(value: bool) -> None: ...
def is_offline() -> bool: ...
def load_icons(
    icons: Sequence[str],
    *,
    on_finished: Callable[[dict[str, Exception | None]], None] | None = None,
) -> LoadRequest: ...
def default_client() -> IconifyClient: ...

from collections.abc import Callable

class IconifyClient(QObject):
    def __init__(
        self,
        parent: QObject | None = None,
        *,
        offline: bool = False,
    ) -> None: ...
    def set_offline(self, value: bool) -> None: ...
    def is_offline(self) -> bool: ...
    def get_failure(self, icon: str) -> Exception | None: ...
    def reset_failures(self) -> None: ...
    def ensure_loaded(self, icon: str) -> None: ...
    def load(
        self,
        icons: Sequence[str],
        *,
        on_finished: Callable[[dict[str, Exception | None]], None] | None = None,
    ) -> LoadRequest: ...
    def close(self) -> None: ...

class LoadRequest(QObject):
    def names(self) -> tuple[str, ...]: ...
    def wait(self, timeout_ms: int | None = None) -> dict[str, Exception | None]: ...
    def cancel(self) -> None: ...
